pipeline {
    agent any

    triggers {
    pollSCM("* * * * *")
    }

    stages {
        stage("Build"){
            steps{
                echo "Building"
                    sh "cd API"
                    sh "dotnet build"
                
            }
        }
        stage("run k6 test"){
                    steps{
                        echo "K6 testing"
                        dir("/__tests__"){
                        sh "k6 version"
                        sh "k6 run performance-test.js"
                        }
                    }
                }
    }
}