pipeline {
    agent any

    triggers {
    pollSCM("* * * * *")
    }



    stages {
        stage("Check versions"){
            steps{
               echo "Checking versions"
               sh "docker --version"
            }
        }

        stage("Build"){
            steps{
                echo "Building"
                    sh "dotnet build"
            }
        }
        
        stage("k6 performance testing"){
             steps{
                echo 'Installing k6'
                sh "sudo -S "
                sh 'sudo chmod +x setup_k6.sh'
                sh 'sudo ./setup_k6.sh'
                echo 'Running K6 performance tests...'
                sh 'k6 run tests/performance-test.js'
            }
        }
      
    }
}